Repository atom-community/atom, pull requests merged in 2020-07, with the labels that each got.

#30 CI: Use Cache@2 task in place of Lighthouse
  script/vsts/platforms/linux.yml
  script/vsts/platforms/macos.yml
  script/vsts/platforms/windows.yml
Labels: CI

#32 no PR triggers on release builds
  script/vsts/release-branch-build.yml
Labels: CI

#36 Set up Azure DevOps config files to look for our fork, not upstream, enable automated releases
  script/vsts/get-release-version.js
  script/vsts/lib/release-notes.js
  script/vsts/nightly-release.yml
  script/vsts/pull-requests.yml
  script/vsts/release-branch-build.yml
  script/vsts/upload-artifacts.js
Labels: CI

#45 CI: GITHUB_TOKEN to fix vscode-ripgrep downloading issues
  script/vsts/platforms/templates/bootstrap.yml
Labels: CI

#46 CI templates
  script/vsts/nightly-release.yml
  script/vsts/platforms/linux.yml
  script/vsts/platforms/macos.yml
  script/vsts/platforms/templates/bootstrap.yml
  script/vsts/platforms/templates/build.yml
  script/vsts/platforms/templates/cache.yml
  script/vsts/platforms/templates/download-unzip.yml
  script/vsts/platforms/templates/preparation.yml
  script/vsts/platforms/templates/publish.yml
  script/vsts/platforms/templates/test.yml
  script/vsts/platforms/windows.yml
  script/vsts/release-branch-build.yml
Labels: CI

#52 :arrow_up: etch@0.14.0
  package-lock.json
  package.json
Labels: experiment

#53 Package symbolic link
  src/package-manager.js
Labels: experiment

#31 Parallelize Tests
  script/test
  script/vsts/platforms/macos.yml
  script/vsts/platforms/templates/test.yml
  script/vsts/platforms/windows.yml
  src/main-process/start.js
Labels: CI, Tests

#59 Bump settings view
  package-lock.json
  package.json
Labels: experiment

#60 Bump find replace
  package-lock.json
  package.json
Labels: experiment

#63 collect console log in renderer tests
  script/test
Labels: CI, Tests

#62 support ES6 default require for packages
  src/package.js
Labels: Atom Packages, Modernization, enhancement

#68 CI: Faster GetReleaseVersion and Release/Upload Artifacts jobs
  script/vsts/nightly-release.yml
  script/vsts/pull-requests.yml
  script/vsts/release-branch-build.yml
Labels: CI

#71 detect symbolic link packages
  src/package-manager.js
Labels: bug

#73 ⬆️ electron@6.1.12
  package-lock.json
  package.json
  script/lib/package-application.js
  script/package-lock.json
  script/package.json
  script/vsts/platforms/templates/bootstrap.yml
  script/vsts/platforms/templates/preparation.yml
  script/vsts/windows-run.js
  spec/integration/helpers/start-atom.js
  src/crash-reporter-start.js
  src/module-cache.js
Labels: Modernization, enhancement
