Repository atom-community/atom, pull requests merged in 2020-08, with the labels that each got.

#74 enable multi-threading on Atom
  src/main-process/atom-window.js
Labels: enhancement, performance

#78 Fix miscellaneous ci issues
  script/vsts/get-release-version.js
  script/vsts/lib/release-notes.js
  script/vsts/nightly-release.yml
  script/vsts/platforms/linux.yml
  script/vsts/platforms/windows.yml
  script/vsts/pull-requests.yml
  script/vsts/release-branch-build.yml
  script/vsts/upload-artifacts.js
Labels: CI

#79 CI: Move GetReleaseVersion to its own template
  script/vsts/nightly-release.yml
  script/vsts/platforms/templates/get-release-version.yml
  script/vsts/pull-requests.yml
  script/vsts/release-branch-build.yml
Labels: CI

#88 Switch apm to @atom-ide-community/atom-package-manager
  apm/package-lock.json
  apm/package.json
Labels: Modernization

#103 update: apm@2.5.2-atomic.1
  apm/package-lock.json
  apm/package.json
Labels: Modernization, dependencies

#44 Build Windows with MSVC 2019
  script/vsts/nightly-release.yml
  script/vsts/platforms/templates/preparation.yml
  script/vsts/platforms/windows.yml
  script/vsts/release-branch-build.yml
Labels: CI, Modernization

#108 Merge upstream master
  spec/integration/helpers/start-atom.js
  src/config-schema.js
  src/main-process/atom-window.js
Labels: :arrow_heading_down: pull upstream

#121 Merge upstream master
  CONTRIBUTING.md
  packages/incompatible-packages/styles/incompatible-packages.less
  script/vsts/nightly-release.yml
  script/vsts/platforms/templates/bootstrap.yml
  script/vsts/platforms/templates/cache.yml
  script/vsts/platforms/templates/preparation.yml
  script/vsts/release-branch-build.yml
  src/package.js
Labels: :arrow_heading_down: pull upstream

#123 Tests: Refactor spawnTest
  script/test
Labels: Tests

#109 CI: Windows: Build with MSVC 2017 and test on 2019
  script/vsts/platforms/windows.yml
Labels: CI, bug

#122 Retry timed out steps automatically
  script/test
Labels: Tests
