Repository atom-community/atom, pull requests merged in 2020-09, with the labels that each got.

#132 Upstream master
  apm/package-lock.json
  package-lock.json
  package.json
Labels: :arrow_heading_down: pull upstream

#136 update: apm@2.5.2-atomic.2
  apm/package-lock.json
  apm/package.json
Labels: Modernization, dependencies

#145 update apm@2.5.2-atomic.3
  apm/package-lock.json
  apm/package.json
Labels: dependencies

#153 Upstream master
  package-lock.json
  package.json
  packages/about/package-lock.json
  script/build
  script/package-lock.json
  script/vsts/platforms/linux.yml
  script/vsts/platforms/macos.yml
  script/vsts/platforms/templates/build.yml
  script/vsts/platforms/templates/preparation.yml
  script/vsts/platforms/templates/publish.yml
  script/vsts/platforms/windows.yml
  spec/main-process/atom-window.test.js
  src/config-schema.js
  src/main-process/atom-window.js
Labels: :arrow_heading_down: pull upstream

#156 Parallel Bootstrap
  script/bootstrap
  script/build
  script/config.js
  script/lib/install-apm.js
  script/lib/install-script-dependencies.js
  script/lib/install-script-runner-dependencies.js
  script/script-runner/package-lock.json
  script/script-runner/package.json
  script/vsts/platforms/templates/cache.yml
Labels: performance

#159 Retry timed out tests more
  script/test
Labels: Tests

#160 update: @aminya/electron-link@^0.6.3"
  script/package-lock.json
  script/package.json
Labels: dependencies

#163 Upstream master
  package-lock.json
  package.json
  script/package-lock.json
  script/package.json
  script/vsts/nightly-release.yml
  script/vsts/package-lock.json
  script/vsts/platforms/templates/get-release-version.yml
  script/vsts/platforms/windows.yml
  script/vsts/release-branch-build.yml
Labels: :arrow_heading_down: pull upstream

#168 Update branch automatically using rebase bot
  .github/rebase.yml
Labels: CI

#129 Update hard-coded GitHub URLs to be dynamic
  packages/about/lib/update-manager.js
  packages/about/spec/update-manager-spec.js
  script/lib/create-windows-installer.js
  script/lib/update-dependency/git.js
  script/lib/update-dependency/pull-request.js
Labels: CI, medium-priority

#174 Upstream master
  package-lock.json
  package.json
  script/package-lock.json
  script/vsts/package-lock.json
  script/vsts/platforms/windows.yml
Labels: :arrow_heading_down: pull upstream

#175 linux dpkg-deb: speed up build
  script/lib/create-debian-package.js
  script/vsts/platforms/templates/preparation.yml
Labels: CI, performance

#182 Upstream master
  package-lock.json
  package.json
  packages/dalek/package-lock.json
  packages/dalek/package.json
  packages/dalek/test/dalek.test.js
  script/test
  spec/main-process/atom-application.test.js
  spec/main-process/atom-window.test.js
  spec/main-process/file-recovery-service.test.js
  spec/text-editor-registry-spec.js
Labels: :arrow_heading_down: pull upstream

#188 Upstream master
  package-lock.json
  package.json
  script/lib/update-dependency/pull-request.js
  src/main-process/main.js
  src/main-process/parse-command-line.js
  src/panel-container-element.js
Labels: :arrow_heading_down: pull upstream

#190 exclude test folders from the packaged app
  script/lib/include-path-in-packaged-app.js
Labels: performance

#194 Upstream master
  apm/package-lock.json
  package-lock.json
  package.json
  script/lib/include-path-in-packaged-app.js
  script/package-lock.json
  src/color.js
Labels: :arrow_heading_down: pull upstream
